### ISSUE TITLE
Error inflating class ... FYI android.deliveryboy.com is name of my development project

### ISSUE THREAD

**Issue by maven-y** [amlashi-sadra/AwesomeSpinner#11]
**Crash Log**

> 2019-01-09 12:23:00.492 6982-6982/android.deliveryboy.com E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android.deliveryboy.com, PID: 6982
    android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class android.deliveryboy.com.utils.AwesomeSpinner
    Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.deliveryboy.com.utils.AwesomeSpinner
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.deliveryboy.com.DeliveryHistory.onCreateView(DeliveryHistory.java:47)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #40: Binary XML file line #40: Error inflating class com.isapanah.awesomespinner.spinnerDefaultSelection
     Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class com.isapanah.awesomespinner.spinnerDefaultSelection
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.isapanah.awesomespinner.spinnerDefaultSelection" on path: DexPathList[[zip file "/data/app/android.deliveryboy.com-xeo6aBpNQOnNBlQiAKFzwg==/base.apk"],nativeLibraryDirectories=[/data/app/android.deliveryboy.com-xeo6aBpNQOnNBlQiAKFzwg==/lib/x86, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:23166)
        at android.deliveryboy.com.utils.AwesomeSpinner.init(AwesomeSpinner.java:58)
2019-01-09 12:23:00.493 6982-6982/android.deliveryboy.com E/AndroidRuntime:     at android.deliveryboy.com.utils.AwesomeSpinner.<init>(AwesomeSpinner.java:49)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.deliveryboy.com.DeliveryHistory.onCreateView(DeliveryHistory.java:47)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**XML**

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/white"
    android:orientation="vertical"
    android:padding="10dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:layout_marginLeft="20dp"
        android:layout_marginRight="20dp"
        android:orientation="vertical">

        <android.deliveryboy.com.utils.AwesomeSpinner
            android:id="@+id/spinner"
            android:layout_width="match_parent"
            android:layout_height="45dp"
            android:background="@drawable/spinner_bg" />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="5dp"
            android:orientation="horizontal"
            android:weightSum="2">

            <Button
                android:layout_width="match_parent"
                android:layout_height="45dp"
                android:layout_marginRight="3dp"
                android:layout_weight="1"
                android:background="#F2F2F2"
                android:drawableLeft="@drawable/calenda"
                android:padding="7dp"
                android:text="DD / MM / YY"
                android:textColor="#B5B5B5" />

            <Button
                android:layout_width="match_parent"
                android:layout_height="45dp"
                android:layout_marginLeft="3dp"
                android:layout_weight="1"
                android:background="#F2F2F2"
                android:drawableLeft="@drawable/calenda"
                android:padding="7dp"
                android:text="DD / MM / YY"
                android:textColor="#B5B5B5" />
        </LinearLayout>

    </LinearLayout>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipToPadding="false"
        android:scrollbars="vertical"
        tools:listitem="@layout/current_deliveries_items" />

</LinearLayout>

**java code**

    package android.deliveryboy.com;

    import android.app.ProgressDialog;
    import android.deliveryboy.com.utils.AwesomeSpinner;
    import android.deliveryboy.com.utils.Global;
    import android.os.AsyncTask;
    import android.os.Bundle;
    import android.support.v4.app.Fragment;
    import android.support.v7.app.AppCompatActivity;
    import android.support.v7.widget.DefaultItemAnimator;
    import android.support.v7.widget.DividerItemDecoration;
    import android.support.v7.widget.LinearLayoutManager;
    import android.support.v7.widget.RecyclerView;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.AdapterView;
    import android.widget.ArrayAdapter;
    import android.widget.LinearLayout;
    import android.widget.ListView;
    import android.widget.Spinner;

    import org.json.JSONArray;
    import org.json.JSONException;
    import org.json.JSONObject;

    import java.util.ArrayList;
    import java.util.HashMap;
    import java.util.Iterator;
    import java.util.Map;

    import static android.deliveryboy.com.utils.Global.URL;

    public class DeliveryHistory extends Fragment {

    RecyclerView recyclerView;
    android.support.v7.app.ActionBar actionBar;
    ProgressDialog dialog;
    View view;
    String fromTimeStamp = "";
    String toTimeStamp = "";
    String cashMode="1";
    ArrayList<HashMap<String,String>> list = new ArrayList<HashMap<String, String>>();

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.delivery_history, container, false);

        actionBar = ((AppCompatActivity) getActivity()).getSupportActionBar();
        actionBar.setTitle("Delivery History");

        String[] arraySpinner = new String[] {"CASH", "ONLINE"};
        AwesomeSpinner s = (AwesomeSpinner) view.findViewById(R.id.spinner);
        
        return view;

    }

### Can you please help me into this ?

**Comment by sadra** [comment]
Seems you are using another library. You should open your issue on this repo: [https://github.com/vanshikaarora/DeliveryBoy](https://github.com/vanshikaarora/DeliveryBoy)

**Comment by maven-y** [comment]
You are wrong

 # deliveryboy 

 is the name of my project.

I just put your class AwesomeSpinner in my util package : below is everything you want to verify 

/**
     * Created by sadra on 5/26/17.
     */

    package android.deliveryboy.com.utils;

    import android.content.Context;
    import android.content.res.Resources;
    import android.content.res.TypedArray;
    import android.deliveryboy.com.R;
    import android.graphics.Color;
    import android.graphics.PorterDuff;
    import android.support.v7.widget.AppCompatButton;
    import android.util.AttributeSet;
    import android.util.Log;
    import android.view.Gravity;
    import android.view.View;
    import android.widget.AdapterView;
    import android.widget.ArrayAdapter;
    import android.widget.ImageView;
    import android.widget.RelativeLayout;

    /**
     * Created by sadra on 5/26/17.
     */

    public class AwesomeSpinner extends RelativeLayout {

    private AppCompatButton _hintButton;
    private spinnerDefaultSelection _spinner;
    private ImageView _downArrow;
    private ArrayAdapter<String> _spinnerAdapterString;
    private ArrayAdapter<CharSequence> _spinnerAdapterCharSequence;
    private boolean _allowToSelect;
    private onSpinnerItemClickListener<String> _callback;
    private static final String TAG = AwesomeSpinner.class.getSimpleName();
    private boolean _isItemResourceDeclared = false;
    private int _spinnerType = 0;
    private boolean _isSelected;
    private int HINT_BUTTON_NOT_SELECTED_COLOR = Color.parseColor("#aaaaaa");
    private final int HINT_BUTTON_DISABLED_COLOR = Color.parseColor("#BDBDBD");
    private int HINT_BUTTON_COLOR = Color.BLACK;
    private final int DOWN_ARROW_DEFAULT_TINT_COLOR = Color.parseColor("#797979");
    private int DOWN_ARROW_TINT_COLOR = Color.parseColor("#797979");

    public AwesomeSpinner (Context context) {
        super(context);
        init(null);
    }

    public AwesomeSpinner (Context context, AttributeSet attrs) {
        super(context, attrs);
        init(attrs);
    }

    public AwesomeSpinner (Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init(attrs);
    }

    private void init(AttributeSet attrs) {
        inflate(getContext(), R.layout.spinner_view, this);
        this._hintButton = (AppCompatButton) findViewById(R.id.awesomeSpinner_hintButton);
        this._spinner = (spinnerDefaultSelection) findViewById(R.id.awesomeSpinner_spinner);
        this._downArrow = (ImageView) findViewById(R.id.awesomeSpinner_downArrow);

        if(attrs != null){
            setSpinnerStyle(getContext().obtainStyledAttributes(attrs, R.styleable.AwesomeSpinnerStyle, 0, 0));
        }

    }

    private void setSpinnerStyle(TypedArray typedArray){

        setHintButtonText(typedArray.getString(R.styleable.AwesomeSpinnerStyle_spinnerHint));

        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
        params.setMargins(10,40,10,10);
        switch (typedArray.getInt(R.styleable.AwesomeSpinnerStyle_spinnerDirection, 0)){
            case 0:
                _hintButton.setGravity(Gravity.LEFT | Gravity.CENTER_VERTICAL);
                params.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
                _downArrow.setLayoutParams(params);
                break;
            case 1:
                _hintButton.setGravity(Gravity.RIGHT | Gravity.CENTER_VERTICAL);
                params.addRule(RelativeLayout.ALIGN_PARENT_LEFT);
                _downArrow.setLayoutParams(params);

                break;
        }

    }

    public void setAdapter(ArrayAdapter<String> adapter){
        this._spinnerAdapterString = adapter;
        _spinner.setAdapter(_spinnerAdapterString);
        initiateSpinnerString();
    }

    public void setAdapter(ArrayAdapter<CharSequence> adapter, int idle){
        _spinnerType = 1;
        this._spinnerAdapterCharSequence = adapter;
        _spinner.setAdapter(_spinnerAdapterCharSequence);
        initiateSpinnerCharSequence();
    }

    public boolean isSelected(){
        return _isSelected;
    }

    private void initiateSpinnerString(){

        if(!_isItemResourceDeclared){
            _spinnerAdapterString.setDropDownViewResource(R.layout.spinner_list_item);
        }

        _spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

                Log.d(TAG, "position selected: " + position);
                if (AwesomeSpinner.this._callback == null) {
                    throw new IllegalStateException("callback cannot be null");
                }
                if(_allowToSelect){
                    _isSelected = true;
                    Object item = AwesomeSpinner.this._spinner.getItemAtPosition(position);
                    AwesomeSpinner.this._callback.onItemSelected(position, (String) item);
                    setHintButtonText(_spinner.getSelectedItem().toString());
                }
                _allowToSelect = true;

            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                Log.d(TAG, "Nothing selected");
            }
        });


    }

    private void initiateSpinnerCharSequence(){

        if(!_isItemResourceDeclared){
            _spinnerAdapterCharSequence.setDropDownViewResource(R.layout.spinner_list_item);
        }

        _spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

                Log.d(TAG, "position selected: " + position);
                if (AwesomeSpinner.this._callback == null) {
                    throw new IllegalStateException("callback cannot be null");
                }
                if(_allowToSelect){
                    _isSelected = true;
                    Object item = AwesomeSpinner.this._spinner.getItemAtPosition(position);
                    AwesomeSpinner.this._callback.onItemSelected(position, (String) item);
                    setHintButtonText(_spinner.getSelectedItem().toString());
                }
                _allowToSelect = true;

            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                Log.d(TAG, "Nothing selected");
            }
        });


    }

    public void setDropDownViewResource(int resource){

        if(_spinnerType == 1){
            _spinnerAdapterCharSequence.setDropDownViewResource(resource);
        }else{
            _spinnerAdapterString.setDropDownViewResource(resource);
        }

        _isItemResourceDeclared = true;

    }

    public void setOnSpinnerItemClickListener(onSpinnerItemClickListener<String> callback){

        this._callback = callback;

        _hintButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                _spinner.performClick();
            }
        });
    }

    public void setSelection(int position){
        _allowToSelect = true;
        _spinner.setSelection(position);
    }

    public void setSelection(String value){
        if(value.trim().isEmpty()){
            _allowToSelect = true;
            if(_spinnerType == 0){
                int spinnerPosition = _spinnerAdapterString.getPosition(value);
                _spinner.setSelection(spinnerPosition);
            }else{
                int spinnerPosition = _spinnerAdapterCharSequence.getPosition(value);
                _spinner.setSelection(spinnerPosition);
            }
        }
    }

    public String getSelectedItem(){
        if(isSelected()){
            return _spinner.getSelectedItem().toString();
        }else{
            return null;
        }
    }

    public spinnerDefaultSelection getSpinner(){
        return _spinner;
    }

    public int getSelectedItemPosition(){
        return _spinner.getSelectedItemPosition();
    }

    public interface onSpinnerItemClickListener<T> {
        /**
         * When a spinner item has been selected.
         *
         * @param position Position selected
         * @param itemAtPosition Item selected
         */
        void onItemSelected(int position, T itemAtPosition);
    }

    public void setSpinnerEnable(boolean enable){
        this._spinner.setEnabled(enable);
        this._hintButton.setEnabled(enable);
        setDownArrowStyle();
        setHitButtonStyle();
    }

    public boolean isSpinnerEnable(){
        return this._spinner.isEnabled();
    }

    private void setHitButtonStyle(){
        this._hintButton.setTextColor(
                this._hintButton.isEnabled() ?
                        (isSelected() ? HINT_BUTTON_COLOR : HINT_BUTTON_NOT_SELECTED_COLOR)
                        :
                        HINT_BUTTON_DISABLED_COLOR
        );
    }

    public void setHintTextColor(int color){
        this.HINT_BUTTON_NOT_SELECTED_COLOR = color;
        this._hintButton.setTextColor(isSelected() ? this.HINT_BUTTON_COLOR : this.HINT_BUTTON_NOT_SELECTED_COLOR);
    }

    public void setSelectedItemHintColor(int color){
        this.HINT_BUTTON_COLOR = color;
        this._hintButton.setTextColor(isSelected() ? this.HINT_BUTTON_COLOR : this.HINT_BUTTON_NOT_SELECTED_COLOR);
    }

    private void setHintButtonText(String label){
        _hintButton.setText(label);
        setHitButtonStyle();
    }

    private void setDownArrowStyle(){
        this._downArrow.setColorFilter(
                this._hintButton.isEnabled() ? this.DOWN_ARROW_TINT_COLOR : this.DOWN_ARROW_DEFAULT_TINT_COLOR,
                PorterDuff.Mode.SRC_ATOP);
        this._downArrow.setAlpha(this._hintButton.isEnabled() ? 1.0f : 0.6f);
    }

    public void setDownArrowTintColor(int color){
        this.DOWN_ARROW_TINT_COLOR = color;
        setDownArrowStyle();
    }

    }



# Hope this helps

**Comment by sadra** [comment]
Please follow the instruction, implement the library and test it again: [README.md](https://github.com/sadra/AwesomeSpinner/blob/master/README.md)

**Comment by maven-y** [comment]
Can you tell me Do I need to change anything in your widget to use it in Fragment ??
